services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/php-app
    depends_on:
      - php
      - mysql-php-app
  php:
    container_name: php-php-app
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/php-app
    user: '1000:1000'
  mysql-php-app:
    container_name: mysql-php-app
    image: mysql    
    volumes: 
      - ./mysql-php-app:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - mysql.env
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 1500:80
    environment: 
      - PMA_HOST=mysql-php-app
    depends_on:
      - mysql-php-app

volumes:
  mysql-php-app: